# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sort-Key-DateTime
version:      0.03
version_from: lib/Sort/Key/DateTime.pm
installdirs:  site
requires:
    DateTime:                      0.28
    Sort::Key:                     0.01
    Test::More:                    0.54

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
