--- #YAML:1.0
name:               Sort-Key-DateTime
version:            0.07
abstract:           Perl extension for sorting objects by some DateTime key
author:
    - Salvador Fandino <sfandino@yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:    0.28
    Sort::Key:   1.28
    Test::More:  0.54
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
